config/routes.rb
Rails.application.routes.draw do
root 'sessions#home'

  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create' 
 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/transactions/find' => 'transactions#find'

  resources :categories
  resources :transactions

  resources :budgets do
    resources :transactions, only: [:new, :show]
    resources :categories, only: [:new, :show]
  end 

  resources :users do
    resources :transactions, only: [:show, :index, :new, :create, :edit, :update]
    resources :budgets, only: [:show, :index, :new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user 
  has_many :transactions
  has_many :categories, through: :transactions
  
  validates :name, presence: true, uniqueness: {scope: [:user_id]}
  validates :income, presence: true
  validates :expenses, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :find_budget, only: [:show, :edit, :update]
    helper_method :remaining_money, :excess_income

    def index 
        @budgets = current_user.budgets
    end 

    def new
        @budget = Budget.new(user_id: params[:user_id])  
    end 

    def create
        @budget = current_user.budgets.build(budget_params)
        if @budget.save
           redirect_to budget_path(@budget)
        else 
          flash[:alert] = "Budget did not save. Please try again."
          render :new 
        end

    end 

    def show 
        @transactions = current_user.transactions
        # @budget_start_date = @budget.start_date
        # @budget_end_date = @budget.end_date
        # @monthly_transactions = Transaction.where('date' >= @budget_start_date).where('date' >= @budget_start_date)
        # binding.pry
    end 

    def edit
    end 

    def update
        @budget.update(budget_params)
        redirect_to user_budget_path(current_user)
    end 

    def destroy 
        Budget.find(params[:id]).destroy
        redirect_to user_budgets_path(current_user)
    end 


    private
    
    def budget_params
        params.require(:budget).permit(:name, :income, :expenses, :start_date, :end_date, :content, :notes, category_ids:[], categories_attributes: [:name])
    end 

    def excess_income
        @budget.income - @budget.expenses
    end 

    def remaining_money
        excess_income - total_spent
    end 
    
    def find_budget
        @budget = Budget.find(params[:id])
    end 

end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<div class="grey-text">
<h2>Budget Form </h2>
</div>

<%= form_for(@budget) do |f|%>

<% if @budget.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @budget.errors.full_messages.each do |msg| %> 
      <li class="flash-alert">* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.label :income %>
<%= f.number_field :income, step: :any %>
<br>
<br>
<%= f.label :expenses %>
<%= f.number_field :expenses, step: :any %>
<br>
<br>
<%= f.label :start_date %>
<%= f.date_field :start_date %>
<br>
<br>
<%= f.label :end_date %>
<%= f.date_field :end_date %>
<br>
<br>
<%= f.label :notes %>
<%= f.text_field :notes %>
<br>
<br>
<%= f.submit%>
<% end %>

app/views/budgets/edit.html.erb
<%= render 'form', budget: Budget.find(params[:id]) %>

app/views/budgets/index.html.erb
<div class="grey-text">
<h3> <%= current_user.name%>'s Honest Budgets </h3>
</div>
<br>

<% if @budgets == [] %>
<br>
<br>

  <div class="row">
    <div class="col s12 m12">
      <div class="card grey">
        <div class="card-content white-text">
          <span class="card-title">You have not created a Budget.</span>
        </div>
        <div class="card-action black-text">
          <%= link_to "Create a New Budget", new_budget_path, method:'get'  %>
        </div>
      </div>
    </div>
  </div>


<% else %>

<table class="striped highlight center">
  <thead>
    <th>Name</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Delete?</th>
  </thead>

  <tbody>

    <% @budgets.each do |budget|%>
        <tr>
            <td> <%= link_to budget.name, user_budget_path(current_user, budget) %></td>
            <td>  <%= budget.start_date.strftime('%a %b %d, %Y') %> </td>
            <td>  <%= budget.end_date.strftime('%a %b %d, %Y') %> </td>
            <td> <%= link_to "Delete Budget", budget, method: :delete, data: { confirm: "Are you sure?", disable_with: "Processing..." } %> </td>
        </tr>
    <% end %>

  </tbody>
</table>
<% end %>

app/views/budgets/new.html.erb
<%= render 'form', budget: Budget.new %>

app/views/budgets/show.html.erb
<br>
<div class="row">
    <div class="center">
      <div class="card grey">
        <div class="card-content white-text">
          <span class="card-title"><%= @budget.name %> Budget </span>
          <p> Start Date: <%= @budget.start_date.strftime('%b %d, %Y') %> </p>
          <p> End Date: <%= @budget.end_date.strftime('%b %d, %Y') %> </p>
          <br>
          <p> Income: <%= number_to_currency(@budget.income)%> </p>
          <p> Expenses: <%= number_to_currency(@budget.expenses) %> </p>
          <br>
          <p> Excess Income: <%= number_to_currency(excess_income) %></p>
          <br>
          <p> Total Spent: <%= number_to_currency(total_spent) %></p>
          <p> Remaining Income: <%= number_to_currency(remaining_money)%></p>
          <br>
          <p>Notes: <%= @budget.notes %> </p>
        </div>
        <div class="card-action">
         <p> <%= link_to "Add New Budget Transaction", new_budget_transaction_path(@budget.id), method:'get'  %> </p>
         <p> <%= link_to "Edit Budget", edit_user_budget_path(current_user), method:'get'  %> </p>
         <p> <%= link_to "Delete Budget", @budget, method: :delete, data: { confirm: "Are you sure?", disable_with: "Processing..." } %> </p>
        </div>
      </div>
    </div>
  <% if @transactions == [] %>
      <div class="col s6 m12">
        <div class="card grey">
          <div class="card-content white-text">
            <span class="card-title">You have no transactions stored.</span>
          </div>
          <div class="card-action black-text">
            <%= link_to "Add New Budget Transaction", new_transaction_path, method:'get'  %>
          </div>
        </div>
      </div>
        <% else %>

          <table class="centered">
            <thead>
            <th>Store Name</th>
            <th>Amount</th>
            <th>Date</th>
            <th>Category</th>
          </thead>

          <tbody>
          <% @transactions.each do |transaction|%>
              <tr>
                  <td> <%= transaction.store_name %></td>
                  <td> <%= link_to number_to_currency(transaction.amount), user_transaction_path(current_user, transaction) %> </td>
                  <td> <%= transaction.date.strftime('%a %b %d, %Y') %></td>
                  <td> <%= find_transaction_category(transaction.category_id) %></td>
              </tr>
          <% end %>

          </tbody>
        </table>
      <% end %>
</div>        

        