config/routes.rb
Rails.application.routes.draw do
root 'sessions#home'

  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create' 
 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/transactions/find' => 'transactions#find'

  resources :categories
  resources :transactions

  resources :budgets do
    resources :transactions, only: [:new, :show]
    resources :categories, only: [:new, :show]
  end 

  resources :users do
    resources :transactions, only: [:show, :index, :new, :create, :edit, :update]
    resources :budgets, only: [:show, :index, :new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions
  has_many :budgets, through: :transactions
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
      @categories = Category.all
    end

    def new
      @category.new
    end 

    def show
      @category = Category.find(params[:id])
    end

    def edit
    end 
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.submit%>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form', category: Category.new %>

app/views/categories/index.html.erb
<div class="lighten-1">
<h3> <%= current_user.name%>'s Budget Categories </h3>
</div>
<br>

<% if @categories == [] %>
<br>
<br>

  <div class="row">
    <div class="col s12 m6">
      <div class="card grey darken-4">
        <div class="card-content white-text">
          <span class="card-title">You have no categories created.</span>
        </div>
        <div class="card-action">
          <%= link_to "Add a New Category", new_category_path, method:'get'  %>
        </div>
      </div>
    </div>
  </div>


<% else %>
    
      <div class="card grey lighten-2">
        <span class="white-text">    
        <% @categories.each do |category|%>
        <ul>
            <li> <%= category.name %></li>
        </ul>
    <% end %>
        </span>
      </div>
    


<% end %>


<form action="/categories/new" method="get">
  <label for="fname">Add a New Category:</label><br>
  <input type="text" name="name"><br>
  <input type="submit" value="Submit">
</form>

app/views/categories/new.html.erb
<%= render 'form', category: Category.new(name: "") %>