config/routes.rb
Rails.application.routes.draw do
root 'sessions#home'

  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create' 
 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/transactions/find' => 'transactions#find'

  resources :categories
  resources :transactions

  resources :budgets do
    resources :transactions, only: [:new, :show]
    resources :categories, only: [:new, :show]
  end 

  resources :users do
    resources :transactions, only: [:show, :index, :new, :create, :edit, :update]
    resources :budgets, only: [:show, :index, :new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :find_transaction, only: [:show, :edit, :update]

    def index 
        @transactions = current_user.transactions
    end 

    def find 
        @category = Category.find_by(name: params[:transaction][:category_id])
        @transactions = Transaction.by_category(@category, current_user)
        render :index 
    end

    def new
        if params[:budget_id]  == nil 
          @transaction = Transaction.new
          render :new 
        else 
          @transaction = Transaction.new(budget_id: params[:budget_id])
          render :new 
        end  
    end 

    def create  
        @transaction = current_user.transactions.build(transaction_params)
        @budget = Budget.find_by(name: transaction_params[:budget_id])
        @transaction.budget_id = @budget.id
        @category = Category.find_or_create_by(name: transaction_params[:category_id])
        @category.transactions << @transaction
       
        if @transaction.save
           show_transaction
        else
          flash[:alert] = "Transaction did not save. Please try again."
          render :new 
        end

    end 

    def show 
    end 

    def edit
    end 

    def update 
        if @transaction.update(transaction_params)
        show_transaction
        else 
          flash[:alert] = "Transaction did not update. Please try again."
          render :edit
        end 
    end 

    def destroy 
        Transaction.find(params[:id]).destroy
        redirect_to user_transactions_path(current_user)
    end 


    private
    
    def transaction_params
        params.require(:transaction).permit(:store_name, :amount, :date, :user_id, :budget_id, :category_id, category_attributes: [:name], budget_attributes: [:name])
    end 

    def find_transaction
        @transaction = Transaction.find(params[:id])
    end 

    def show_transaction
        redirect_to transaction_path(@transaction)
    end 

end

app/helpers/transactions_helper.rb
module TransactionsHelper
    
end

app/views/transactions/_form.html.erb
<div class="grey-text">
<h3> Transaction Form </h3>
</div>
<br>

<%= form_for(@transaction) do |f|%> 

<% if @transaction.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @transaction.errors.full_messages.each do |msg| %> 
      <li class="flash-alert">* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= f.hidden_field :user_id, :value => current_user.id %>

<%= f.label :store_name %>
<%= f.text_field :store_name %><br>
<br>
<%= f.label :date %>
<%= f.date_field :date %><br>
<br>
<%= f.label :amount %>
<%= f.number_field :amount, step: :any %><br>
<br>

 <%= f.label "Budget" %>
      <%= f.text_field :budget_id, list: "budget_autocomplete" %>
        <datalist id= "budget_autocomplete"> 
            <% user_budgets.each do |budget|%>
                <option value="<%= budget.name %>">  </option>
            <%end%>
        </datalist>

<br>
  <%= f.label "Pick an Existing Category or Type in a New Category" %>
      <%= f.text_field :category_id, list: "category_autocomplete" %>
        <datalist id= "category_autocomplete"> 
            <% Category.all.each do |category|%>
                <option value="<%= category.name %>"> </option>
            <%end%>
        </datalist>
<br>
<br>
<%= f.submit%>
<% end %>

app/views/transactions/edit.html.erb
<%= render 'form', transaction: Transaction.find(params[:id]) %>

app/views/transactions/index.html.erb
<div class="grey-text">
<h3> <%= current_user.name%>'s Transactions </h3>
</div>

<div class="grey-text">
<h4> Total Spent: <%= number_to_currency(total_spent) %> </h4>
</div>
<br>

<% if @transactions == [] %>
<br>
<br>

  <div class="row">
    <div class="col s12 m12">
      <div class="card grey">
        <div class="card-content white-text">
          <span class="card-title">You have no transactions stored.</span>
        </div>
        <div class="card-action black-text">
          <%= link_to "Add a New Transaction", new_transaction_path, method:'get'  %>
        </div>
      </div>
    </div>
  </div>


<% else %>

<div class="grey-text">
<p> Filter by Category: </p>

<form action="/transactions/find" method="get">
  <input type="text" id="category_id" name="transaction[category_id]"><br>
 
  <input type="submit" value="Filter">
</form>

</div>
<br>
<br>

<table class="striped highlight center">
  <thead>
    <th>Store Name</th>
    <th>Amount</th>
    <th>Date</th>
    <th>Category</th>
  </thead>

  <tbody>
    <% @transactions.each do |transaction|%>
        <tr>
            <td> <%= transaction.store_name %></td>
            <td> <%= link_to number_to_currency(transaction.amount), user_transaction_path(current_user, transaction)%></td>
            <td> <%= transaction.date.strftime('%a %b %d, %Y') %></td>
            <td><%= find_transaction_category(transaction.category_id) %></td>
        </tr>
    <% end %>

    </tbody>
</table>

<% end %>

app/views/transactions/new.html.erb
<%= render 'form', transaction: Transaction.new %>

app/views/transactions/show.html.erb
<br>
<br>
<div class="row">
    <div class="col s12 m12">
      <div class="card grey">
        <div class="card-content white-text">
          <span class="card-title"><%= @transaction.store_name %></span>
            <p> Date: <%= @transaction.date.strftime('%a %b %d, %Y') %> </p>
            <p> Amount: <%= number_to_currency(@transaction.amount) %> </p>
            <p> Category: <%= find_transaction_category(@transaction.category_id) %></p>
        </div>
        <div class="card-action">
          <%= link_to "Edit Transaction", edit_user_transaction_path(current_user), method:'get'  %> 
          <%= link_to "Delete Transaction", @transaction, method: :delete, data: { confirm: "Are you sure?", disable_with: "Processing..." } %> 
        </div>
      </div>
    </div>
</div>