config/routes.rb
Rails.application.routes.draw do
root 'sessions#home'

  get '/signup' => 'users#new', as: 'signup'
  post '/signup' => 'users#create' 
 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/transactions/find' => 'transactions#find'

  resources :categories
  resources :transactions

  resources :budgets do
    resources :transactions, only: [:new, :show]
    resources :categories, only: [:new, :show]
  end 

  resources :users do
    resources :transactions, only: [:show, :index, :new, :create, :edit, :update]
    resources :budgets, only: [:show, :index, :new, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HonestBudget</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
  </head>

<main>
  <body>
    
    
    <nav class="nav">
     <div class="nav-wrapper grey">
     <a href="/" class="brand-logo">// HNST BDGT //</a>

      <% if is_logged_in? %>

        <ul>
        
        <li class="right"><%= link_to "New Budget", new_user_budget_path(current_user), method:'get' %></li>
        <li class="right"><%= link_to "All Budgets", user_budgets_path(current_user), method:'get'  %></li> 
        <li class="right"><%= link_to "All Transactions", user_transactions_path(current_user), method:'get' %></li> 
        <li class="right"><%= link_to "Logout", logout_path, method:'delete' %></li> 
        </ul>
      <% else %>
        <ul>
        
        <li class="right"><%= link_to "Sign Up", signup_path, method:'get' %></li> 
        <li class="right"><%= link_to "Log In", login_path, method:'get' %></li> 
        </ul>
      <% end %>
        
      
     </div>
    </nav>

    <%if flash[:alert]  %>
        <div class="alert alert-danger" role="alert">
     <%=  flash[:alert] %> 
        </div>
    <% end %>


    <div class="container center">

      <%= yield %>

    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  </body>
  </main>
  <br>
  <br>

  <footer class="page-footer center grey">
    <div>
        © 2020 Honest Budget
    <div>
  </footer>
</html>